### ISSUE TITLE
Invalid login links when working locally

### ISSUE THREAD

**Issue by ryanjbonnell** [aaemnnosttv/wp-cli-login-command#18] opened 2017-05-26 19:21 UTC
When developing locally, it's a common practice to pull down a fresh copy of the production MySQL database before beginning any new work.

For instance, the production site may be `example.com`, but the local environment may be setup to use `example.dev`, as overridden in `wp-config.php`:

```
define( 'WP_HOME',    'http://' . $_SERVER['HTTP_HOST'] );
define( 'WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] );
```

Since it's not always feasible or possible to use a tool like [WP Migrate DB Pro][1] or [WP-CLI Search & Replace][2], so often times the `wp_options` table will still have the production values for `siteurl` or `home`:

| option_name | option_value       |
|-------------|--------------------|
| site_url    | http://example.com |
| home        | http://example.com |

Why does this matter?

By default WP-CLI Login Command uses the value in the database, so when working locally and running a command like `wp login as zerocool --launch` will return a Magic Login Link similar to:

```
http://example.com/c39808ec/47c4db-7dc7d05a4d-40b4b4a036
```

Instead, what is desired is for WP-CLI Login Command to use the _local_ WordPress Site URL, not what is necessarily in the database, such as:

```
http://example.dev/c39808ec/47c4db-7dc7d05a4d-40b4b4a036
```

It appears [\WP_CLI_Login\LoginCommand::domain()][4] is responsible for determining the URL used for the login links:

```
 return parse_url(home_url(), PHP_URL_HOST);
```

While it’s possible to use the [`home_url()`][3] filter to alter this behavior, it would desirable for WP-CLI Login Command to handle this logic _”magically”_, so the package and companion plugin could be installed and used with zero configuration.

[1]: https://deliciousbrains.com/wp-migrate-db-pro/
[2]: https://github.com/wp-cli/search-replace-command
[3]: https://codex.wordpress.org/Function_Reference/home_url
[4]: https://github.com/aaemnnosttv/wp-cli-login-command/blob/master/src/LoginCommand.php#L475

**Comment by aaemnnosttv** [comment] 2017-05-26 21:03
Thanks for your detailed request!  The problem is that the login command generates a login link which will only work for the domain it is used on for security purposes.  For that reason, the command needs to know the domain ahead of time.

I'm not quite sure if it's possible for the command to resolve what the domain is locally without using core functions.  If you defined the `WP_HOME` with `http://example.dev` locally it would work as expected.

The current `dev-master` version of the command includes support for using WP-CLI's `--url` option. You can use this to set the home url that should be used for generating the login link. This is useful for multisite as well as local dev using something like the `wp server` command. This will work in your case as well.

Update to the latest version of the command with 

```
wp package install aaemnnosttv/wp-cli-login-command
```

Then try logging in locally like so:
```
wp login as zerocool --url=http://example.dev --launch
```

I realize this probably isn't as zero-configuration as you'd like but I'm not sure it is possible to do much less than that. Please keep in mind that the login command is designed to be usable in production, not just for local development.

**Comment by ryanjbonnell** [comment] 2017-05-27 02:31
This is a fantastic idea and _just may work_.

When running the login command with the url parameter specified, I'm successfully taken to the ”magic link” in my default browser using the correct site URL.

```
$ wp login as zerocool --url=http://example.dev --launch
```

However, instead of being automatically logged-in, I'm shown an error message:

![screenshot][1]

> **The attempted magic login has expired or already been used.**
>
> Try again perhaps? or Go Home →

Do you have any idea what's causing the error message or how it can be fixed?

Tested with WordPress 4.7.5, WP CLI Login Command Server v1.2 and WP-CLI v1.1.0 on macOS 10.12.5 "Sierra".

[1]: https://cloud.githubusercontent.com/assets/133372/26517204/9d7856de-4248-11e7-8b2f-c79e4429732a.png

**Comment by aaemnnosttv** [comment] 2017-05-27 19:40
I'm having a hard time reproducing what you're seeing.

What does `home_url()` return on `example.dev`?

**Comment by ryanjbonnell** [comment] 2017-05-28 06:27
```
var_dump( home_url() );

string(13) "https://example.dev"
```

**Comment by ryanjbonnell** [comment] 2017-06-27 15:26
While this issue is being sorted out, I opted to use Daniel Bachhuber's [One Time Login][1] plugin to allow me to login as any WordPress user from the WP-CLI:

`$ wp user one-time-login admin --url=http://example.dev`

Taking it one step further, we can pipe the result from One-Time Login and launch our default browser using the "magic" login link:

`$ wp user one-time-login admin --url=http://example.dev | grep -Eoh '(http|https)://.*' | xargs open`

[1]: https://runcommand.io/wp/user-one-time-login/

**Comment by aaemnnosttv** [comment] 2020-03-14 10:00
Closing this one out as this seems to be an edge case.

Anyone is free to re-open with more details as to how this can be reproduced on the latest version 👍

**Closed by aaemnnosttv** 2020-03-14 10:00 UTC
